num = int(input('Digite um número para ver sua tabuada: '))

print(num, 'x', 1, '=', '{}'.format(num * 1))
print(num, 'x', 2, '=', '{}'.format(num * 2))
print(num, 'x', 3, '=', '{}'.format(num * 3))
print(num, 'x', 4, '=', '{}'.format(num * 4))
print(num, 'x', 5, '=', '{}'.format(num * 5))
print(num, 'x', 6, '=', '{}'.format(num * 6))
print(num, 'x', 7, '=', '{}'.format(num * 7))
print(num, 'x', 8, '=', '{}'.format(num * 8))
print(num, 'x', 9, '=', '{}'.format(num * 9))
print(num, 'x', 10, '=', '{}'.format(num * 10))